<?xml version="1.0"?>
<package format="3">
  <name>can_driver</name>
  <version>2.0.0</version>
  <description>ROS 2 CAN driver for DCLab boards and VESC and RoboMaster motors.</description>
  <maintainer email="soubungit@gmail.com">DCLab</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>custom_messages</exec_depend>
  <exec_depend>python3-can</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
